{{- if .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "application.labels" . | indent 4 }}
{{ include "application.labels.chart" . | indent 4 }}
{{- if .Values.deployment.additionalLabels }}
{{ toYaml .Values.deployment.additionalLabels | indent 4 }}
{{- end }}
    tags.datadoghq.com/env: "${ENVIRONMENT}"
    tags.datadoghq.com/service: "${RELEASE_NAME}"
    tags.datadoghq.com/version: "${GIT_TAG}"
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ include "application.labels.selector" . | indent 6 }}
{{- if .Values.deployment.strategy }}
  strategy:
{{ toYaml .Values.deployment.strategy | indent 4 }}
{{- end }}
  template:
    metadata:
      labels:
{{ include "application.labels.selector" . | indent 8 }}
{{- if .Values.deployment.podLabels }}
{{ toYaml .Values.deployment.podLabels | indent 8 }}
{{- end }}
        tags.datadoghq.com/env: "${ENVIRONMENT}"
        tags.datadoghq.com/service: "${RELEASE_NAME}"
        tags.datadoghq.com/version: "${GIT_TAG}"
    spec:
      {{- if .Values.deployment.hostAliases }}
      hostAliases:
{{ toYaml .Values.deployment.hostAliases | indent 6 }}
      {{- end }}
      {{- if .Values.deployment.initContainers }}
      initContainers:
{{ toYaml .Values.deployment.initContainers | indent 6 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.deployment.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
{{ toYaml .Values.deployment.tolerations | indent 8 -}}
      {{- end }}
      {{- if .Values.deployment.affinity }}
      affinity:
      {{ toYaml .Values.deployment.affinity | indent 8 -}}
      {{- end }}
      {{- if .Values.deployment.imagePullSecrets }}      
      imagePullSecrets:
      - name: {{ .Values.deployment.imagePullSecrets }}
      {{- end }}
      containers:
      - name: {{ template "application.name" . }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        {{- if .Values.deployment.containerSecurityContext }}
        securityContext:      
{{ toYaml .Values.deployment.containerSecurityContext | indent 10 }}
          {{- end }}
        {{- if .Values.deployment.envFrom }}
        envFrom:
        {{- range .Values.deployment.envFrom }}
        {{- if (eq .type "configmap") }}
        - configMapRef:
            {{- if .name }}
            name: {{ .name }}
            {{- else }}
            name: {{ template "application.name" $ }}
            {{- end }}
        {{- end }}
        {{- if (eq .type "secret") }}
        - secretRef:
            {{- if .name }}
            name: {{ .name }}
            {{- else }}
            name: {{ template "application.name" $ }}
            {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        env:
          {{- if .Values.deployment.env }}
{{ toYaml .Values.deployment.env | indent 10 }}
          {{- end }}
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_VERSION
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/version']

{{- if .Values.deployment.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.deployment.livenessProbe | indent 10 }}
{{- end }}
{{- if .Values.deployment.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.deployment.readinessProbe | indent 10 }}
{{- end }}
        volumeMounts:
        {{- if (and (eq .Values.persistence.enabled true) (eq .Values.persistence.mountPVC true) ) }}
        - mountPath: {{ .Values.persistence.mountPath }}
          name: {{ template "application.name" . }}-data
        {{- end }}
        {{- if .Values.deployment.volumeMounts }}
{{ toYaml .Values.deployment.volumeMounts | indent 8 }}
        {{- end }}
        - mountPath: /var/run/datadog
          name: apmsocketpath

{{- if .Values.deployment.resources }}
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
{{- end }}
        {{- if .Values.deployment.additionalContainers }}
{{ toYaml .Values.deployment.additionalContainers | indent 6 }}
        {{- end }}
        {{- if .Values.deployment.securityContext }}
      securityContext:      
{{ toYaml .Values.deployment.securityContext | indent 8 }}
          {{- end }}

      volumes:
        {{- if (and (eq .Values.persistence.enabled true) (eq .Values.persistence.mountPVC true) ) }}
      - name: {{ template "application.name" . }}-data
        persistentVolumeClaim:
          claimName: {{ template "application.name" . }}-data
        {{- end }}
        {{- if .Values.deployment.volumes }}
{{ toYaml .Values.deployment.volumes | indent 6 }}
        {{- end }}

      - name: apmsocketpath
        hostPath:
          path: /var/run/datadog/

      {{- if .Values.rbac.serviceAccount.name }}
      serviceAccountName: {{ .Values.rbac.serviceAccount.name }}
        {{- else }}
      serviceAccountName: {{ template "application.name" . }}
      {{- end }}
{{- end }}