{{- if and .Values.endpointMonitor .Values.endpointMonitor.enabled }}
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  labels:
{{ include "application.labels" $ | indent 4 }}
{{ include "application.labels.chart" $ | indent 4 }}
{{- if .Values.endpointMonitor.additionalLabels }}
{{ toYaml .Values.endpointMonitor.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.endpointMonitor.annotations }}
  annotations:
{{ toYaml .Values.endpointMonitor.annotations | indent 4 }}
{{- end }}
  name: {{ template "application.name" $ }}
spec:
{{- if .Values.endpointMonitor.spec }}
{{ toYaml .Values.endpointMonitor.spec | indent 2 }}
{{- end }}
{{- end }}