{{- if .Values.autoscaling }}
{{- if and .Values.autoscaling.enabled .Values.deployment }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "application.name" . }}
  labels:
    {{ include "application.labels" . | nindent 4 }}
    {{ include "application.labels.chart" . | nindent 4 }}
  {{- if .Values.autoscaling.additionalLabels }}
    {{- toYaml .Values.autoscaling.additionalLabels | nindent 4 }}
  {{- end }}
  {{- if .Values.autoscaling.annotations }}
  annotations:
    {{- toYaml .Values.autoscaling.annotations | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "application.name" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- range .Values.autoscaling.metrics }}
    - type: {{ .type }}
      resource:
        name: {{ .resource.name }}
        target:
          type: Utilization
          {{- if eq .resource.name "cpu" }}
          averageUtilization: {{ .resource.targetAverageUtilization | default 70 }}
          {{- else if eq .resource.name "memory" }}
          averageUtilization: {{ .resource.targetAverageUtilization | default 80 }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}