{{- if .Values.vaultStaticSecret }}
{{- if .Values.vaultStaticSecret.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.vaultStaticSecret.name }}
  namespace: {{ .Values.vaultStaticSecret.namespace }}
spec:
  destination:
    name: {{ .Values.vaultStaticSecret.destination.name }}
    create: {{ .Values.vaultStaticSecret.destination.create }}
    overwrite: {{ .Values.vaultStaticSecret.destination.overwrite }}
  mount: {{ .Values.vaultStaticSecret.mount }}
  path: {{ .Values.vaultStaticSecret.path }}
  refreshAfter: 10s
  type: kv-v2
  vaultAuthRef: platform/vault-auth
{{- end }}
{{- end }}
