name: Test Helm Template

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  helm-template-test:
    name: Helm Template Render and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.13.0' # Use desired version

      - name: Template Helm Chart
        run: |
          cd stable/application-helm
          helm template --skip-tests -f ./values.yaml ./ > application.yaml
          cat application.yaml
